# Generated by Django 3.2.12 on 2022-04-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminid', models.IntegerField()),
                ('adminaccesslevel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='genItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=20)),
                ('itemquantity', models.IntegerField()),
                ('itemposX', models.IntegerField()),
                ('itemposY', models.IntegerField()),
                ('itemposZ', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='genUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernick', models.CharField(max_length=15)),
                ('userid', models.IntegerField()),
                ('userlastconnection', models.DateField()),
                ('userposX', models.IntegerField()),
                ('userposY', models.IntegerField()),
                ('userposZ', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='genVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiclemodel', models.CharField(max_length=30)),
                ('vehicleposX', models.IntegerField()),
                ('vehicleposY', models.IntegerField()),
            ],
        ),
    ]
