# Generated by Django 3.2.13 on 2022-05-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaIntermedia', '0002_auto_20220507_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='genadmin',
            name='createdby',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='genadmin',
            name='lastmodifiedby',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='genitem',
            name='createdby',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='genitem',
            name='lastmodifiedby',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='genuser',
            name='createdby',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='genuser',
            name='lastmodifiedby',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='genvehicle',
            name='createdby',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='genvehicle',
            name='lastmodifiedby',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
