# Generated by Django 3.2.13 on 2022-05-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaFinal', '0003_auto_20220507_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
