# Generated by Django 3.2.13 on 2022-05-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaFinal', '0004_remove_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
